version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
    links:
      - zookeeper

  db:
    image: postgres:16
    container_name: kafka_db
    environment:
      - POSTGRES_USER=t1_school_admin
      - POSTGRES_PASSWORD=1234
